name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'

    - name: Build
      run: |
        # إنشاء مجلد android
        flutter create --org com.flexyemen --project-name flex_yemen --platforms android .
        
        # إضافة flutterEmbedding
        sed -i '/<application>/a \        <meta-data android:name="flutterEmbedding" android:value="2" />' android/app/src/main/AndroidManifest.xml
        
        # رفع minSdkVersion
        sed -i 's/minSdkVersion [0-9]*/minSdkVersion 21/' android/app/build.gradle
        
        # بناء APK
        flutter pub get
        flutter build apk --release --split-per-abi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/*.apk
